### ISSUE TITLE
Config runner view is partially displayed

### ISSUE THREAD

**Issue by gwladysdembelle** [rey5137/robot-runner-plugin#90]
I have IntelliJ IDEA 2023.1.2 (Ultimate Edition), and when I try to configure Robot Framework tests, the window doesn't display in its entirety. I can't, among other things, select the "Output directory" and if I resize the view, it doesn't change. Is this due to a version incompatibility?

**Comment by rey5137** [comment]
I've release version 0.5.0 that should fix this issue. Pls try it.
